version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:latest
    environment:
      ApiKey: ${{ ApiKey }}
      PlaylistID: ${{ PlaylistID }}
      WebhookUrl: ${{ WebhookUrl }}
      EmbedText: VideoURL
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: 
          name: "Run YTPDW"
          command: echo $WebhookUrl && python3 ./main.py
          

workflows:
  main:
    jobs:
      - build-and-test
