# This is a basic workflow to help you get started with Actions

name: Some tests

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Cache pip
        uses: actions/cache@v2
        with: 
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cahce for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os}}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. 
          flake8 . --count --exit-zero --max-complexity=10 --statistics
      - name: Run tests
        run: |
          python test.py
      - name: Run the script, send all videos
        run: |
          python main.py --offset 99999999
        env:
          ApiKey: ${{ secrets.ApiKey }}
          PlaylistID: PLB2AcRG34VQWlArTnlLR98RZeOnep8-Zb
          WebhookUrl: ${{ secrets.WebhookUrl }}
          EmbedText: Test script running...
